apiVersion: v1
kind: Secret
metadata:
  name: portal-secrets
type: Opaque
data:
  # Values must be Base64 encoded in a YAML file
  # You can generate these by running: echo -n "password" | base64
  keycloak-db-password: {{ "cGFzd29vb3Jk" | b64enc | quote }}
  keycloak-admin-password: {{ "cGFzd29vb3Jk" | b64enc | quote }}
  ghost-db-password: {{ "cGFzd29vb3Jk" | b64enc | quote }}
  smtp-password: {{ "xfjx iloq fbbc clmg" | b64enc | quote }}
  oauth2-client-secret: {{ "nQzE2CNiAA9UolQKAW7JudEFxhEk0xXX" | b64enc | quote }}
  oauth2-cookie-secret: {{ "Y29va2llc2VjcmVldHZhbHVl" | b64enc | quote }}
  ghost-admin-api-key: {{ "69dd0009a9972c000140b6f4:1241e39b00191d898cb287edb5b870d678676cc01461ee3ccb3c6bf9dc4c269d" | b64enc | quote }}
                                                  
